### PR TITLE
Telegram Bot

### PR DESCRIPTION
**Pull request by MrDrakeTN**
Can we make just one Telegram Bot with multiple account.
Maybe we will have command like: /stats [username]
Thank you!

### CODE REVIEW

**Comment by lucasvieceli** [comment]
this bot was not programmed to accept multi account in a single instance,

you can use the server I'm developing

https://t.me/bombcryptoFreeBot

**Comment by MrDrakeTN** [comment]
Can we choose map: Treasure Hunt or Amazon Survival?

**Comment by lucasvieceli** [comment]
I didn't feel like developing the new mode yet.

**Comment by MrDrakeTN** [comment]
Can you show me how to read data and maybe I will update this bot?
Thank you!

**Comment by lucasvieceli** [comment]
I'm going to develop the new mode, today I can't because the bomb is unstable

**Comment by MrDrakeTN** [comment]
> I'm going to develop the new mode, today I can't because the bomb is unstable

thank for your help!

**Comment by lucasvieceli** [comment]
> > I'm going to develop the new mode, today I can't because the bomb is unstable
> 
> thank for your help!

it's working

**Comment by kielhyre** [comment]
Teria como criar para o Discord em vez do telegram? @lucasvieceli

**Comment by lucasvieceli** [comment]
> Teria como criar para o Discord em vez do telegram? @lucasvieceli

no

**Comment by LeartPinheiro** [comment]
@lucasvieceli qual seria o modelo para colocar [MODE_AMAZON] no .env?

**Comment by lucasvieceli** [comment]
> @lucasvieceli qual seria o modelo para colocar [MODE_AMAZON] no .env?

se vc quiser q funcione com modo amazon coloque
MODE_AMAZON=1

se não quiser, não informe

**Pull request merged**
